version: '3'
services:
  service:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile-prod
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./movies_admin/config/.env.prod
    depends_on:
      - database
  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./movies_admin/config/.env.prod.db
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - service
    ports:
      - 80:80
  etl:
      build:
        context: ./etl
        dockerfile: Dockerfile-prod
      env_file:
        - ./etl/config/.env.prod
      depends_on:
        - database
        - elasticsearch
        - redis
      restart: always
  elasticsearch:
    image: elasticsearch:8.5.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      USE_SSL: false
      xpack.security.enabled: false
  redis:
    image: redis:latest
    expose:
      - 6379
volumes:
  postgres_data:
  static_volume:
  media_volume: