version: '3'
services:
  service:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile-prod
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./movies_admin/config/.env.prod
    depends_on:
      - database
  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./movies_admin/config/.env.prod.db
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - service
    ports:
      - 80:80
volumes:
  postgres_data:
  static_volume:
  media_volume: